# Generated by Django 4.2.27 on 2026-02-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_uploaded_at_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='acte_naissance',
            field=models.FileField(blank=True, null=True, upload_to='documents/actes/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='diplome',
            field=models.FileField(blank=True, null=True, upload_to='documents/diplomes/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/photos/'),
        ),
    ]
