# Generated by Django 4.2.27 on 2026-02-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_acte_naissance_alter_document_diplome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='admin_comment',
            field=models.TextField(blank=True, help_text="Raison du refus (visible par l'étudiant)", null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_refused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='acte_naissance',
            field=models.FileField(blank=True, null=True, upload_to='actes/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='diplome',
            field=models.FileField(blank=True, null=True, upload_to='diplomes/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
